third/third/urls.py
from django.contrib import admin
from django.urls import path
from thirdApp import views
from django.conf.urls import include

urlpatterns = [
    path('',views.homepage,name="homepage"),
    path('admin/', admin.site.urls),
    path('thirdApp/',include('thirdApp.urls')),
    path('logout/',views.user_logout,name="user_logout"),
]

third/thirdApp/urls.py
from thirdApp import views
from django.urls import path

app_name = 'thirdApp'

urlpatterns = [
    path('other/',views.page_1,name="page_1"),
    path('relative_url_template/',views.page_2,name="page_2"),
    path('registrate/',views.form_page,name="form_page"),
    path('login/',views.user_login,name="user_login"),
]

third/thirdApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,
        on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

third/thirdApp/forms.py
from django import forms
from thirdApp.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model  = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

third/thirdApp/views.py
from django.shortcuts import render
from django import forms

from thirdApp.models import UserProfileInfo
from thirdApp.forms import UserProfileInfoForm,UserForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def homepage(request):
    my_dict = {'one':'hello','two':100}
    return render(request,"thirdApp/index.html",context=my_dict)

def page_1(request):
    return render(request,"thirdApp/other.html")

def page_2(request):
    return render(request,"thirdApp/relative_url_template.html")

@login_required
def user_logout(request):
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('homepage'))

@login_required
def special(request):
    HttpResponse("You are logged in !")

def form_page(request):

    registered = False

    # CHECK IF WE GET A POST BACK
    if request.method == 'POST':
        # IN WHICH CASE WE PASS IN THAT REQUEST
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        #CHECK IF FORM IS VALID
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request,"thirdApp/registrate.html",
        {'form_user':user_form,
        'form_profile':profile_form,
        'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('homepage'))
            else:
                return HttpResponse("Your account is not active")
        else:
            print("Someone tried log in with username {} and password {}".format(username,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request,"thirdApp/login.html")

third/templates/thirdApp/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Basic Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'homepage' %}">Home page</a></li>
            <li><a class="navbar-link" href="{% url 'thirdApp:page_1' %}">Other page</a></li>
            <li><a class="navbar-link" href="{% url 'thirdApp:page_2' %}">Relative page</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin page</a></li>
            <li><a class="navbar-link" href="{% url 'thirdApp:form_page' %}">Registration page</a></li>
            <li><a class="navbar-link" href="{% url 'thirdApp:user_login' %}">Login page</a></li>
            {% if user.is_authenticated %}
              <li><a class="nav-link" href="{% url 'user_logout' %}">Logout</a></li>
            {% else %}
              <li><a class="nav-link" href="{% url 'thirdApp:user_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>

<!-- EVERYTHING EXCEPT THIS WILL BE INHERITED WITH EXTEND -->
    {% block body_block %}
      <p>WELCOME ON BASIC PAGE ! </p>
      <p>You can go to other sites</p>
    {% endblock %}
  <!--  SO LETS GO INHERIT BASIC HTML-->

  </body>
</html>

third/templates/thirdApp/index.html
<!DOCTYPE html>
{% extends "thirdApp/basic.html" %}

{% block body_block %}
    <h1 align="center">WELCOME TO HOME PAGE!</h1>
    <h2 align="center">THIS WAS UPDATED</h2>
    <h3>updated again ...</h3>
    <a href="{% url 'thirdApp:page_1' %}">Link to other page</a>
     <h5>{{ one|upper }}</h5>
     <h5>{{ two|add:"44" }}</h5>
{% endblock %}

third/templates/thirdApp/login.html
<!DOCTYPE html>

{% extends "thirdApp/basic.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>LOG IN</h1>
    <form action="{% url 'thirdApp:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholde="username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="button" value="Proceed">

    </form>
  </div>
</div>



{% endblock %}

third/templates/thirdApp/other.html
<!DOCTYPE html>
{% extends "thirdApp/basic.html" %}

{% block body_block %}
    <h1>WELCOME ON OTHER PAGE!</h1>
    <a href="{% url 'thirdApp:page_2' %}">Link to relative page</a>
{% endblock %}

third/templates/thirdApp/registrate.html
<!DOCTYPE html>
{% extends "thirdApp/basic.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered  %}
    <h1>Thank you for your registration!</h1>
  {% else %}
    <h1>Fill out next form to register</h1>
    <form enctype="multipart/form-data" method="POST" >
      {% csrf_token %}

      {{ form_user.as_p }}
      {{ form_profile.as_p}}
      <input type="submit" name="" value="Register !!!">
    </form>

  {% endif %}

</div>

{% endblock %}

third/templates/thirdApp/relative_url_template.html
<!DOCTYPE html>
{% extends "thirdApp/basic.html" %}

{% block body_block %}
  {% load staticfiles %}

    <h1>WELCOME TO RELATIVE_URL_TEMPLATE PAGE!</h1>
    <a href="{% url 'thirdApp:page_1' %}">Back to other page</a>
    <br>
    <a href="{% url 'homepage' %}">Link to home page</a>
    <br>
    <a href="{% url 'admin:index' %}"><img src="{% static 'images/admin.jpg' %}" alt="ups,not found" width="150" height="110" border="3"></a>

{% endblock %}